stages:
  - deploy

deploy:
  image: python:latest
  only: [master]
  stage: deploy
  script:
  - pip install awscli
  - aws s3 cp ./**/*.js s3://snake.ahouts.com/
  - aws s3 cp ./**/*.html s3://snake.ahouts.com/
  - aws s3 cp ./**/*.css s3://snake.ahouts.com/
  - aws cloudfront create-invalidation --distribution-id E2XHP9ZZZDCQ3W --paths '/*'
