stages:
  - deploy

deploy:
  image: python:latest
  only: [master]
  stage: deploy
  script:
  - pip install awscli
  - aws s3 cp ./script.js s3://names.mc.ahouts.com/
  - aws s3 cp ./index.html s3://names.mc.ahouts.com/
  - aws s3 cp ./style.css s3://names.mc.ahouts.com/
  - aws cloudfront create-invalidation --distribution-id E2XHP9ZZZDCQ3W --paths '/*'
